# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget Tools'

- task: NuGetCommand@2
  displayName: 'Restore nuget packages'
  inputs:
    restoreSolution: '$(solution)'

- task: Cake@0
  displayName: 'Build Solution: Cake'
  inputs:
    script: 'build.cake'
    target: 'Nuget-Package'
    verbosity: 'Verbose'
    arguments: '-NugetArtifactsPath=$(Build.ArtifactStagingDirectory) -configuration=$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'Build Solution'
  enabled: false
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    createLogFile: true

- task: DotNetCoreCLI@2
  enabled: false
  displayName: 'NUnit Tests: Run'
  inputs:
    command: 'test'
    projects: '$(solution)'

- task: PublishTestResults@2
  displayName: 'NUnit Tests: Publish results'
  enabled: false
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'tests/**/TEST-*.xml'
    mergeTestResults: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  enabled: true
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'